### ISSUE TITLE
Google Cloud Foundation toolkit

### ISSUE THREAD

**Issue by adds68** [finos/compliant-financial-infrastructure#116]
There may be a possibilty to reuse the terraform scripts provided by the GCF toolkit here: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/docs/terraform.md

official guide here: https://services.google.com/fh/files/misc/google-cloud-security-foundations-guide.pdf

**Comment by mcleo-d** [comment]
Cleaning backlog and closing.
