### ISSUE TITLE
Review the accelerator template template

### ISSUE THREAD

**Issue by TLATER** [finos/compliant-financial-infrastructure#125]
Both #97 and #90 made the same mistake of generally documenting their respective services, rather than providing the intended source for Terraform scripts.

We think it makes sense to review the [template](https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md) now that we know the project a bit better, maybe clearing up issues like the ones in those PRs.

**Comment by mcleo-d** [comment]
Cleaning backlog and closing.
