### ISSUE TITLE
Document Pre- and Post- Deployment Automated Checks

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#128]
## Feature Request
Documentation should exist for any automation surrounding terraform.

### Description of Problem:
1. We need to establish concrete decisions regarding what automated checks should be created for pre- and post-deployment of any resources defined in this repository
2. Once the decisions above have been made, documentation should be created for each

Relates to #62, #117, #124, #84

**Comment by mcleo-d** [comment]
@eddie-knight - The CSC project moved to backlog at the end of Sprint 3 #131

@eddie-knight to decide whether to bring into Sprint 4 https://github.com/orgs/finos/projects/1#column-15157368

**Comment by mcleo-d** [comment]
Issue closed as moved forward in OC-CDMC
