### ISSUE TITLE
Cloud Services Needed by CFI for Development and Test

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#135]
## Description 
Access to cloud services have been requested by CSC for development and test purposes. This issue help track of project access to the following platforms in the following order. 

- [x] AWS account and environment to deploy AWS services. 
- [x] GCP account and environment to deploy GCP services - 
  - [x] #219
  - [ ] Red Hat Open Shift - #201
- [ ] Azure account and environment to deploy Azure services.

---
- To have tests, need pipeline. (Pipeline = issue #124)
- To have pipeline, need IaC confidence. (IaC = terraform)
- For IaC confidence, need manual deployment (manual deployment = run locally against existing cloud project using IAM role)
---

**Comment by mcleo-d** [comment]
@maoo working to provision AWS access on behalf of FINOS.

**Comment by mcleo-d** [comment]
AWS account provisioned by @maoo. Thanks! 🚀

**Comment by peterrhysthomas** [comment]
@abdullahgarcia to continue the implementation with @maoo

**Comment by mcleo-d** [comment]
Moved to prioritised until AWS EKS is done and ready to prioritise next cloud service.

**Comment by mcleo-d** [comment]
@AdrianHammond - Do we need a FINOS public GCP instance for the work you're doing with @peterrhysthomas ..?

**Comment by AdrianHammond** [comment]
@mcleo-d  - initially we can do work on my Red Hat GCP instance so having one will not stop progress. How have other teams used FINOS public environment's? @peterrhysthomas

**Comment by thinkl33t** [comment]
Priority is GCP as we already have work in-flight that could use it, then Azure

**Comment by mcleo-d** [comment]
Cleaning backlog and closing.
