### ISSUE TITLE
As a contributor to the Cloud Service Certification project I will add/edit a wiki page by pull request to demonstrate community collaboration

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#15]
### Description of Problem:
In order for documentation contribution to succeed into the CSC GitHub wiki we need to prove pull requests can be raised against wiki documentation by cloning the following link ...

https://github.com/finos/cloud-service-certification.wiki.git

### Potential Solutions:
- Clone the wiki using the wiki repo link above
- Add your name and details to the Project Participants table on the wiki homepage
- Raise a pull request for the page edit to see if the change is possible against current repo settings
- Report findings back to the comments / working group meeting on 16th January 2020
- Educate the group where applicable

**Comment by mcleo-d** [comment]
This item is being solved by the FINOS Open Developer Platform who are also looking for project contributors. Please visit the following issue to get involved with this activity as part of ODP.

https://github.com/finos/open-developer-platform/issues/12

**Comment by eddie-knight** [comment]
Closing this issue as stale.
