### ISSUE TITLE
Maintainers Wanted for Compliant Financial Infrastructure // Formally Cloud Service Certification

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#156]
## Maintainers Wanted for Compliant Financial Infrastructure // Formally Cloud Service Certification

FINOS and the CDMC are pleased to announce the formation of two new projects that unite our joint endeavour for creating pre-certified, open source, cloud services as code and **WE NEED YOU** to lead our cloud service IaC and configuration activity.

Comment on this issue below 👇🏻  if you're a self motivated cloud champion with a passion for AWS, GCP, Azure and other cloud providers who can push forward IaC (Terraform), BDD, OPA, GitHub workflows whilst developing infrastructure as code for certified cloud services.

[Read more about about being a Compliant Financial Infrastructure maintainer here](https://github.com/finos/cloud-service-certification/blob/main/docs/open-roles/cloud-service-certification-project-maintainer.md).

![2021Q4 - FINOS and CDMC](https://user-images.githubusercontent.com/6029572/138253228-71e95267-1808-4e1b-a9cc-da0371f970ea.png)

**Comment by jamilmina1** [comment]
hi

**Comment by RichardWagener365** [comment]
@mcleo-d @thinkl33t - Please note Bob Clough has offered to become a maintainer on the CFI project - Happy to discuss further in todays meeting

**Comment by abdullahgarcia** [comment]
I would like to nominate Bob Clough to become a maintainer on the CFI project.

**Comment by mcleo-d** [comment]
The decision to have a discussion about the maintainer role has been taken prior to voting due to @thinkl33t not being on the call. This is to make sure @thinkl33t is comfortable with responsibilities of the maintainer position.

**Comment by thinkl33t** [comment]
I've had a chat with the current maintainer, and would like to put myself forward as a maintainer for CFI

**Comment by mcleo-d** [comment]
> I've had a chat with the current maintainer, and would like to put myself forward as a maintainer for CFI

Great stuff @thinkl33t - I have added to the agenda for Friday 3rd December #173 and look forward to talking more then 👏🏻 💯 💯 💯 

James 🚀

**Comment by abdullahgarcia** [comment]
I would like to nominate Bob Clough to become a maintainer on the CFI project.

**Comment by eddie-knight** [comment]
+1 for Bob

**Comment by mcleo-d** [comment]
Closing as maintainers recruited.
