### ISSUE TITLE
3rd December 2021 - Compliant Financial Infrastructure Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#173]
## Date
Friday 3rd December 2021 - 10am ET / 3pm GMT

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/compliant-financial-infrastructure/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] Compliant Financial Infrastructure [Project Kanban](https://github.com/orgs/finos/projects/1) Review
- [ ] https://github.com/finos/compliant-financial-infrastructure/discussions/172
- [ ] https://github.com/finos/compliant-financial-infrastructure/discussions/174
- [x] Maintainer recruitment invitation and update ...
  - https://github.com/finos/compliant-financial-infrastructure/issues/156
  - https://github.com/finos/open-compliance-cdmc/issues/1
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/compliant-financial-infrastructure/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email compliant-financial-infrastructure+subscribe@finos.org to subscribe to our mailing list

**Comment by thinkl33t** [comment]
o/

**Comment by timretout** [comment]
Apologies, I cannot make this call today.

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by TLATER** [comment]
o/

**Comment by peterrhysthomas** [comment]
hello

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by RichardWagener365** [comment]
Hi

**Comment by gibsocol** [comment]
Hello!

**Comment by lpaulxvi** [comment]
Howdy!

**Comment by mcleo-d** [comment]
Hello!

**Comment by phriscage** [comment]
Hi

**Comment by balbirthomas** [comment]
Hello all.

**Comment by pedroleaoc** [comment]
Olá!

**Comment by mtronci** [comment]
Hi!

**Comment by tcraigjohnson** [comment]
Good morning from Santa Cruz, California

**Comment by swilliams11** [comment]
hello

**Comment by erictice** [comment]
hello

**Comment by mcleo-d** [comment]
Hi all 👋🏻 

[CDMC_Framework_V1.1.1.pdf](https://github.com/finos/compliant-financial-infrastructure/files/7650814/CDMC_Framework_V1.1.1.pdf) has been added to GitHub Discussion - <a href="https://github.com/finos/compliant-financial-infrastructure/discussions/174">"What is the plan and direction for the CDMC Technical Spec Working Group?"</a>

Drop your name and ideas in GitHub Discussion https://github.com/finos/compliant-financial-infrastructure/discussions/174 to help determine how to implement the CDMC controls in early 2022.

Many thanks,

James.

---
## Cloud Data Management Capabilities Framework
_Best Practices for Managing Data in the Cloud - [CDMC_Framework_V1.1.1.pdf](https://github.com/finos/compliant-financial-infrastructure/files/7650814/CDMC_Framework_V1.1.1.pdf)_

<a href="https://github.com/finos/compliant-financial-infrastructure/files/7650814/CDMC_Framework_V1.1.1.pdf"><img src="https://user-images.githubusercontent.com/6029572/144635425-fb5c92d5-209e-4b40-8bde-6362d19e6589.png" width="400"></a>
