### ISSUE TITLE
17th December 2021 - Informal Community Review : CDMC Cloud Data Management Capabilities Framework

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#176]
## Date
Friday 17th December - 10am ET / 3pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Informal review of the [CDMC Cloud Data Management Capabilities Framework](https://github.com/finos/compliant-financial-infrastructure/files/7650814/CDMC_Framework_V1.1.1.pdf) as found on GitHub Discussion https://github.com/finos/compliant-financial-infrastructure/discussions/174#discussion-3715503
- [x] Providing AWS EKS for the FINOS Legend project. Let's get the groups thoughts before 2022.  
- [x] AOB, Q&A & Adjourn (5mins)

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/compliant-financial-infrastructure/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email compliant-financial-infrastructure+subscribe@finos.org to subscribe to our mailing list

**Comment by thinkl33t** [comment]
Apologies, i'm not going to make this meeting tomorrow.  Hope it goes well!

**Comment by gibsocol** [comment]
Hi everyone.

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by RichardWagener365** [comment]
Hi

**Comment by peterrhysthomas** [comment]
Hi all, happy holidays

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by jamilmina1** [comment]
hi

**Comment by timretout** [comment]
Hello!

**Comment by TLATER** [comment]
o/

**Comment by mcleo-d** [comment]
Hello

**Comment by ojeb2** [comment]
Hi - glad to be talking about CDMC today

**Comment by skoya** [comment]
Hi

**Comment by lpaulxvi** [comment]
Hello

**Comment by erictice** [comment]
Hello
