### ISSUE TITLE
11th February 2022 - Compliant Financial Infrastructure Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#188]
## Date
Friday 11th February 2022 - 10am ET / 3pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/compliant-financial-infrastructure/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Compliant Financial Infrastructure [Project Kanban](https://github.com/orgs/finos/projects/1) Review
  - Congratulations Red Hat and @J0EG for the acceptance and merge of #170 🚀 
- [x] Alternating agendas between Compliant Financial Infrastructure and Open Compliance for CDMC
- [x] Prioritising completion of [AWS EKS](https://github.com/finos/compliant-financial-infrastructure/tree/dev/aws/eks) into Legend and automating deployment / test scenarios for [OpenShift Application Accelerator](https://github.com/finos/compliant-financial-infrastructure/tree/dev/rh/OpenShift/Common)  
- [x] Using Juju Charms on CFI to orchestrate services across CSPs (see Legend and Waltz activity in this space).
  - Further discussion recommended at https://github.com/finos/devops-mutualization/issues/41 with Waltz team.
- [x] Branch protection added with PRs defaulted to `dev`. Documentation update required as requested in issue https://github.com/finos/compliant-financial-infrastructure/issues/167#issuecomment-1035419078
- [ ] AOB, Q&A & Adjourn (5mins)
  - https://github.com/finos/compliant-financial-infrastructure/issues/188#issuecomment-1036322749

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/compliant-financial-infrastructure/

**Mailing List:** Email compliant-financial-infrastructure+subscribe@finos.org to subscribe to our mailing list

**Comment by RichardWagener365** [comment]
Hi

**Comment by jamilmina1** [comment]
Hi

**Comment by kriscanonical** [comment]
Hi

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by erictice** [comment]
Good morning

**Comment by kriscanonical** [comment]
hi

**Comment by AdrianHammond** [comment]
Hi All

**Comment by mcleo-d** [comment]
Hi

**Comment by eddie-knight** [comment]
:shipit: :wave:

**Comment by psiso** [comment]
Hi.

**Comment by ojeb2** [comment]
Hi

**Comment by mcleo-d** [comment]
- https://edmcouncil.org/page/CDMC
- More background on CDMC in this 5min video: https://youtu.be/TIX6kpULUZ4
