### ISSUE TITLE
Provide Feedback on Red Hat Compliance as Code Frameworks and Examples

### ISSUE THREAD

**Issue by anthonygtech** [finos/compliant-financial-infrastructure#19]
Red Hat is committed to enable hybrid/multi-cloud. One aspect of that is compliance as code that works on prem and in multiple public clouds. Any feedback on the following frameworks and examples are appreciated.

OpenSCAP can be used to deliver compliance as code for technical controls:

https://www.open-scap.org/

https://www.open-scap.org/features/scap-components/

Red Hat's SCAP content is stored in the Compliance as Code github repository.
Directory of available content: https://github.com/ComplianceAsCode/content
Red Hat has SCAP content for OpenShift 3. That Red Hat SCAP content is inspired by the CIS Kubernetes v1.2 benchmark, and adjusted as needed to be OpenShift-specific. (You can download CIS benchmarks here: https://www.cisecurity.org/cis-benchmarks/)

1. You can find the list of automated checks available for OpenShift 3 here:
https://github.com/ComplianceAsCode/content/tree/master/ocp3/profiles

2. One of the recommendations in the CIS Kubernetes benchmark is to ensure that the etcd datastore is encrypted. You can find the OVAL code to validate that the OpenShift etcd datastore is encrypted below:
https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/api-server/api_server_encryption_provider_cipher/oval/shared.xml

Finally, if you have access to an OpenShift cluster and you'd like to try out our SCAP content for OpenShift 3, you can find the content here: https://nvd.nist.gov/ncp/checklist/866
and a cheat sheet for using the scanner and content is attached. 

Also, if you haven't done so already, check out the Cloud Security Alliance Cloud Controls Matrix. It provides a terrific view of the overlapping controls across many regulatory and security frameworks. You can download it here: 
https://cloudsecurityalliance.org/research/cloud-controls-matrix/

We'll be working next on building SCAP content for NIST 800-53 controls for OpenShift 4.

**Comment by mcleo-d** [comment]
Cleaning backlog and closing.
