### ISSUE TITLE
22nd April 2022 - Compliant Financial Infrastructure Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#209]
## Date
Friday 22nd April 2022 - 10am ET / 3pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/compliant-financial-infrastructure/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Compliant Financial Infrastructure [Project Kanban](https://github.com/orgs/finos/projects/1) Review
- [x] @AdrianHammond - Let's discuss the following great idea from https://finos-lf.slack.com/archives/C01RNUMC2DP/p1649431000589129
> based on current progress we should be ready to raise a PR for first release of documentation / code for OpenShift on GCP in the next two weeks. I discussed with @peter-thomas-db he suggested that prior to opening the PR that we arrange a session for us to take the team through what we have developed. Is this something people would be interested in? Given the Easter break in the UK I was going to suggest that we looked to schedule sometime the week of the 25th April. Please let me know what you think?
- [x] https://github.com/finos/community/issues/183 - Call for CFI update
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/compliant-financial-infrastructure/

**Mailing List:** Email compliant-financial-infrastructure+subscribe@finos.org to subscribe to our mailing list

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by mcleo-d** [comment]
Hey 👋🏻

**Comment by AdrianHammond** [comment]
Hi All :-)

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by tcraigjohnson** [comment]
Good wonderful morning!

**Comment by robmoffat** [comment]
Rob / FINOS

Hello!

**Comment by jamilmina1** [comment]
hi

**Comment by gibsocol** [comment]
G'day

**Comment by johanalimka** [comment]
Hey all

**Comment by thinkl33t** [comment]
Estoy Aqui

**Comment by lpaulxvi** [comment]
Hello

**Comment by erictice** [comment]
hello
