### ISSUE TITLE
Discussion : AWS EKS - version locking for hashicorp/aws

### ISSUE THREAD

**Issue by thinkl33t** [finos/compliant-financial-infrastructure#218]
https://github.com/finos/compliant-financial-infrastructure/discussions/157

@thinkl33t

**Comment by mcleo-d** [comment]
@thinkl33t to update issue with more context of what needs to be done.

**Comment by mcleo-d** [comment]
@thinkl33t to close Discussion https://github.com/finos/compliant-financial-infrastructure/discussions/157

**Comment by mcleo-d** [comment]
Hi @thinkl33t and @abdullahgarcia  👋🏻 

Is it possible to close this issue before #256 this week?

I know the request is simplistic, but the issue has been open since May '22.

Cheers 👍🏻 

James.

**Comment by eddie-knight** [comment]
This issue will be resolved during the EKS child-module breakout.
