### ISSUE TITLE
3rd June 2022 - Compliant Financial Infrastructure Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#221]
## Date
Friday 3rd June 2022 - 10am ET / 3pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/compliant-financial-infrastructure/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Compliant Financial Infrastructure [Project Kanban](https://github.com/orgs/finos/projects/1) Review
- [x] [Open Source in Finance Hybrid NYC Meetup](https://zoom.us/webinar/register/8016540834337/WN_TcmWGDmDSJ2kpy57gw0N5A) on June 8th 2022
- [x] [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022
- [x] AOB, Q&A & Adjourn (5mins)

## Open Source in Finance Hybrid NYC Meetup, June 8th 2022

June 8th 2022 - Join us for our New York City / hybrid [Open Source in Finance Meetup](https://zoom.us/webinar/register/8016540834337/WN_TcmWGDmDSJ2kpy57gw0N5A) at the Synechron offices in Times Square. Networking will start from 5.30pm, and talks at 6.30pm.

Presentations include ...

- **Stephen Goldbaum**, Executive Director at Morgan Stanley and Lead Maintainer of the FINOS Morphir project
- **Sandeep Kumar**, FinLabs at Synechron. Horizon Scanning of Compliance Regulations (FINRA, ESMA, …)
- **Paul Childerhose**, Member of the Board of Directors at Canadian RegTech Association and Canadian Regional Advocate for the EDM Council.

If you're not able to join us in person, don't worry! **Register below and join us online at 6.30pm**.

👉🏻 [Register to join the NYC meetup here](https://zoom.us/webinar/register/8016540834337/WN_TcmWGDmDSJ2kpy57gw0N5A)

<a href="https://zoom.us/webinar/register/8016540834337/WN_TcmWGDmDSJ2kpy57gw0N5A"><img src="https://user-images.githubusercontent.com/6029572/171235502-c81a890c-ec12-4118-8088-64a1694d0cfd.png" width="85%" /></a>

## Open Source in Finance Forum London, July 13th 2022

Register below for the FINOS [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022 👾💥

Open Source in Finance Forum is the only conference dedicated to driving collaboration and innovation in financial services through open source software and standards.

We bring together experts across financial services, technology, and open source to engage our community in stimulating and thought-provoking conversations about how to best (and safely) leverage open source software to solve industry challenges.

FINOS members employees are eligible to receive complimentary registration as part of their company’s membership. Please email [osff@finos.org](mailto:osff@finos.org) to request the Finos Member access code.

Register and find out more 👉🏻 https://events.linuxfoundation.org/open-source-finance-forum-london/

<a href="https://events.linuxfoundation.org/open-source-finance-forum-london/"><img src="https://user-images.githubusercontent.com/6029572/171230930-a68f99a3-ac8d-4738-8054-87af2d45b544.png" width="85%" /></a>

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/compliant-financial-infrastructure/

**Mailing List:** Email compliant-financial-infrastructure+subscribe@finos.org to subscribe to our mailing list

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by eddie-knight** [comment]
:wave: :shipit:
