### ISSUE TITLE
New SAA workflow, documentation, and template

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#223]
### Description of Problem:
The team has identified difficulties in creating Service Approval Accelerator documents. In order to streamline this work, we have discussed a revised workflow. The revised workflow needs to be clearly articulated via documentation in this repo, and the template should be adjusted to match.

![Untitled Diagram drawio(1)](https://user-images.githubusercontent.com/21176439/174324632-e083add6-434b-43d5-b5ea-a8c8654665b4.png)

### Potential Solutions:

Someone will need to take the lead, with collaboration from the community, to create the necessary documentation and template.

**Comment by AdrianHammond** [comment]
@eddie-knight very happy to get involved / take the lead on this work.  -A-

**Comment by eddie-knight** [comment]
> @eddie-knight very happy to get involved

Thanks Adrian! Could you start by reviewing PR #224?

We will also very likely need to add documentation changes to accompany that template work.
