### ISSUE TITLE
1st July 2022 - Compliant Financial Infrastructure Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#226]
## Date
Friday 1st July 2022 - 10am ET / 3pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/compliant-financial-infrastructure/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Compliant Financial Infrastructure [Project Kanban](https://github.com/orgs/finos/projects/1) Review
- [x] [Open Source in Finance Forum in London](https://events.linuxfoundation.org/open-source-finance-forum-london) on July 13th 2022 - @mcleo-d 
- [x] AOB, Q&A & Adjourn (5mins)

## Open Source in Finance Forum London, July 13th 2022

Register below for the FINOS [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022 👾💥

Open Source in Finance Forum is the only conference dedicated to driving collaboration and innovation in financial services through open source software and standards.

We bring together experts across financial services, technology, and open source to engage our community in stimulating and thought-provoking conversations about how to best (and safely) leverage open source software to solve industry challenges.

FINOS members employees are eligible to receive complimentary registration as part of their company’s membership. Please email [osff@finos.org](mailto:osff@finos.org) to request the Finos Member access code.

Register and find out more 👉🏻 https://events.linuxfoundation.org/open-source-finance-forum-london/

<a href="https://events.linuxfoundation.org/open-source-finance-forum-london/"><img src="https://user-images.githubusercontent.com/6029572/171230930-a68f99a3-ac8d-4738-8054-87af2d45b544.png" width="85%" /></a>

## Decisions Made
- [ ] Decision 1
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/compliant-financial-infrastructure/

**Mailing List:** Email compliant-financial-infrastructure+subscribe@finos.org to subscribe to our mailing list

**Comment by thinkl33t** [comment]
Hi

**Comment by eddie-knight** [comment]
:wave::shipit:

**Comment by mcleo-d** [comment]
Hi everyone  ⚡ 🦖

**Comment by pedroleaoc** [comment]
Hello :wave:

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by shuchitach** [comment]
Hi
