### ISSUE TITLE
EKS Error : Message_: "unsupported Kubernetes version"

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#228]
## Description

The following error is thrown when running the EKS SDLC for the following 2x pull requests.

- #227 
- #216

### Error

https://github.com/finos/compliant-financial-infrastructure/runs/7151705628?check_suite_focus=true#step:7:1363

```
Error: error creating EKS Cluster (cfi-eks): InvalidParameterException: unsupported Kubernetes version
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "f7a67faf-0796-45c7-9418-4d4687746d78"
  },
  ClusterName: "cfi-eks",
  Message_: "unsupported Kubernetes version"
}
```

### Screenshot

![Screenshot 2022-07-01 at 15 31 35](https://user-images.githubusercontent.com/6029572/176917921-5715dc06-0204-4fbf-9a2f-1d536f1b4190.png)

**Comment by eddie-knight** [comment]
> Q: What happens on the end of support date?
>
> A: On the end of support date, you can no longer create new Amazon EKS clusters with the unsupported version. Existing control planes are automatically updated by Amazon EKS to the earliest supported version through a gradual deployment process after the end of support date. After the automatic control plane update, make sure to manually update cluster add-ons and Amazon EC2 nodes. For more information, see [Update the Kubernetes version for your Amazon EKS cluster ](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#update-existing-cluster).

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Comment by abdullahgarcia** [comment]
Version updated.
