### ISSUE TITLE
Modify Openshift SAA to follow new template

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#229]
## Feature Request

The SAA template has been updated per issue #223 in PR #225. As such, we need to update the Openshift SAA to follow the new simplified template.

**Comment by AdrianHammond** [comment]
Hi @eddie-knight  - just wanted to check something on the template changes that came as a result of issue #223  - did the changes to the SAA template in PR #224 get applied as its not clear to me where to get the updated template from as [this](https://github.com/finos/compliant-financial-infrastructure/blob/dev/templates/ServiceApprovalAcceleratorTemplate.md) looks like the old template.  Thanks A

**Comment by eddie-knight** [comment]
@abdullahgarcia  @thinkl33t 
Can we go ahead and merge PR #224? I think that will resolve @AdrianHammond's question here and let the team move forward with this issue

**Comment by eddie-knight** [comment]
> Yeah there's one more typofix in there, once thats done we can merge :)
@thinkl33t

Oh dang. I'm not seeing any more comments on there... what am I overlooking?

**Comment by abdullahgarcia** [comment]
Let's move things forward.

@AdrianHammond , the PR has been merged. Let us know if there are any questions.

**Comment by thinkl33t** [comment]
> > Yeah there's one more typofix in there, once thats done we can merge :)
> > @thinkl33t
> 
> Oh dang. I'm not seeing any more comments on there... what am I overlooking?

Apparently the review was still 'pending' and i couldn't finalize it from github mobile :facepalm:

**Comment by AdrianHammond** [comment]
@eddie-knight @abdullahgarcia @thinkl33t  - Gents - Thanks for progressing PR #224. Please could we get this issue reopened as I still need to do the work to update the OCP Service Accelerator.

**Comment by eddie-knight** [comment]
> @eddie-knight @abdullahgarcia @thinkl33t  - Gents - Thanks for progressing PR #224. Please could we get this issue reopened as I still need to do the work to update the OCP Service Accelerator. 

Done, sorry about the mixup!

**Comment by eddie-knight** [comment]
> Apparently the review was still 'pending' and i couldn't finalize it from github mobile :facepalm: 

GitHub mobile is kicking my butt today as well. I went to quote Adrian's comment and ended up editing it by mistake.

@AdrianHammond ...Sorry for the miscommunication here, and thanks for helping move the OCP work forward!

**Comment by AdrianHammond** [comment]
> > Apparently the review was still 'pending' and i couldn't finalize it from github mobile 🤦
> 
> GitHub mobile is kicking my butt today as well. I went to quote Adrian's comment and ended up editing it by mistake.
> 
> @AdrianHammond ...Sorry for the miscommunication here, and thanks for helping move the OCP work forward!

no worries @eddie-knight

**Comment by mcleo-d** [comment]
Hi @AdrianHammond 👋🏻  

Are you happy to drive this issue update during #256 given the conversation with @eddie-knight and @abdullahgarcia ?

Cheers 🍻 

James.

**Comment by AdrianHammond** [comment]
> 

Yes @mcleo-d

**Comment by AdrianHammond** [comment]
Work started in this fork https://github.com/johanalimka/compliant-financial-infrastructure/tree/ocp_411

In this issue we will complete following: 

- [ ] Update documentation to reflect release of Red Hat OpenShift 4.11
- [ ] Update the service accelerator to reflect PR #224

**Comment by AdrianHammond** [comment]
Making good progress, hope to open PR in next week or so. Review with @peter-thomas-db arranged for 10/11.

**Comment by AdrianHammond** [comment]
#291 opened for this issue. @eddie-knight @thinkl33t @abdullahgarcia  - please someone review / approved. I discussed what Johana and I were doing ith @peter-thomas-db a few weeks ago but didn't take him through the detail. Major change is using new SAA template.

**Comment by abdullahgarcia** [comment]
Reviewed, approved, and merged.
