### ISSUE TITLE
Modify EKS SAA to follow new template

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#230]
## Feature Request
The SAA template has been updated per issue https://github.com/finos/compliant-financial-infrastructure/issues/223 in PR https://github.com/finos/compliant-financial-infrastructure/pull/225. As such, we need to update the EKS SAA to follow the new simplified template.

**Comment by mcleo-d** [comment]
Hey @eddie-knight 👋🏻 

I've applied `help wanted` if you'd like to discuss the issue during #256.

Cheers,

James.

**Comment by abdullahgarcia** [comment]
Addressed in pull request: https://github.com/finos/compliant-financial-infrastructure/pull/279
