### ISSUE TITLE
Split down Terraform monorepo

### ISSUE THREAD

**Issue by ml4** [finos/compliant-financial-infrastructure#239]
### Description of Problem:
When versioning Terraform child module code in GH, use of a monorepo prevents the ability for the community to version each module separately. It is also against vendor best practice, and won't work with members who use the enterprise product.

### Potential Solutions:
Split the Terraform code from this repo into separate Terraform repos. I will add a nomenclature to this issue when I have confirmed one.
References:
- https://www.terraform.io/cloud-docs/registry/publish-modules#preparing-a-module-repository
- https://learn.hashicorp.com/tutorials/terraform/pattern-module-creation?in=terraform/modules

### Terraform Module Repos Created
- https://github.com/finos/cfi-terraform-template-child-module
- https://github.com/finos/cfi-terraform-gcp-ocp
- https://github.com/finos/terraform-aws-eks

### Required Repos
- Add here

**Comment by mcleo-d** [comment]
Hey @ml4 👋🏻 

Can you join #256 this week to discuss how this issue can be taken forward?

Cheers and speak soon,

James.

**Comment by mcleo-d** [comment]
Related to work being done here ... https://github.com/finos/cfi-terraform-template-child-module

**Comment by eddie-knight** [comment]
[ ] - Create repos for child modules as needed, using template repo as base
[ ] - Next module to work is here: https://github.com/finos/compliant-financial-infrastructure/tree/dev/accelerators/kubernetes/eks/tf_cdmc_aws_eks

**Comment by mcleo-d** [comment]
Hey @eddie-knight, @ml4 and @devops-adeel,

There's been some awesome work on this epic that needs to be celebrated. We should let the group know about the new repos and invite contribution and help.

- https://github.com/finos/cfi-terraform-template-child-module
- https://github.com/finos/cfi-terraform-gcp-ocp
- https://github.com/finos/terraform-aws-eks

James.

**Comment by mcleo-d** [comment]
The following repos have been linked to the CFI kanban ...

![Screenshot 2022-10-06 at 15 04 37](https://user-images.githubusercontent.com/6029572/194334046-a7632157-5a70-436a-af5d-9c9630c60b99.png)

**Comment by mcleo-d** [comment]
Allocate issue to @thinkl33t and the `reproducible builds` working group to move forward with new CFI services.

Moving to `prioritised`.

**Comment by eddie-knight** [comment]
Need to tackle Postgres as well for this

**Comment by ml4** [comment]
OK I will take a punt to:

- Create the child module repo for postgres on azure
- Migrate the code out of CFI 
- Rearrange the code to form standard hashicorp advice
- Test

**Comment by ml4** [comment]
Contrary to the OP, the `Terraform Module Repos Created` were:
- terraform-aws-cfi-dynamodb
- terraform-aws-cfi-lambda
- terraform-aws-cfi-redshift
- terraform-aws-cfi-sqs
- terraform-azurerm-cfi-aks
- terraform-azurerm-cfi-postgresql
- terraform-google-cfi-gke
These have now been populated from the requisite CFI repo subdirectories.  A PR to update the latter will be in today.

**Comment by thinkl33t** [comment]
https://github.com/finos/compliant-financial-infrastructure/pull/322 removes the last bits of IaC from cfi's monorepo

**Comment by AdrianHammond** [comment]
All changes made and merged.
