### ISSUE TITLE
Enable Branch Protection on dev branch

### ISSUE THREAD

**Issue by maoo** [finos/compliant-financial-infrastructure#246]
Given that the `dev` branch of this repository is the default one, I'd suggest enabling branch protection in order to avoid direct pushes into it; no need to reviews or other types of protection, but I'll let the CFI team decide on that.

**Comment by abdullahgarcia** [comment]
Hi Mao,

Yes, please go ahead.

Abdullah

**Comment by maoo** [comment]
Thanks for your quick turnaround @abdullahgarcia and @eddie-knight ! All done, closing issue!
