### ISSUE TITLE
Documentation Refresh

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#250]
### Description of Problem:
Many of our community calls have needed to engage similar questions that should have been answered within our documentation 

### Potential Solutions:
We had a call today to compile suggested changes, which I'll document here.

- Avoid unecessarily exclusive language
    - Change "AWS, Azure..." language to simply "infrastructure"
    - Remove any language that implies the project is exclusively cloud focused
- Change the "Business Problem" section to be a subsection of "What's the Value?"
    - The new parent section should also contain subsections for "What's the value provided by this project?" and "What's the value of contributing to this project?" followed at the end by "What's value does this project add to FINOS?" for the business problem
- Any future-tense language should be changed to active or past tense
    - Example: "Our community intends to create" should be "Our community creates"
- Add 1-2 sentences describing how CFI relates to the _Three Lines of Defense_
    -  This can be a third sentence beneath the "what is compliant" header
- Move all documentation related to contributing into linked documents. Create a simple section emphasizing that contributors should spend time reading those docs.
- "Services & Workflows" section should be reworked into a new section "What can I use from CFI?"
- Feature Matrix section needs an overhaul to be compatible with future work (such as Openshift on GCP and non-cloud resources)

**Comment by eddie-knight** [comment]
If anyone has further suggestions or nitpicks, please add them as comments here. I'll work on creating a PR (or PRs) to address these suggestions next week.

**Comment by mcleo-d** [comment]
Hi @eddie-knight 👋🏻 

I have applied the `help wanted` label and moved to `ready for review` for feedback on the issue suggestion by the wider community.

Hope helps?

James.

**Comment by mcleo-d** [comment]
@eddie-knight - Are we ready to move the issue body to the [CFI docs repo](https://github.com/finos/compliant-financial-infrastructure/tree/dev/docs) and point to from the project `README.md`?

**Comment by AdrianHammond** [comment]
@eddie-knight @abdullahgarcia @thinkl33t 

Just spent some time reading through documentation, below is a list of things that I think we need to update:

[Project Charter](https://github.com/finos/compliant-financial-infrastructure/blob/dev/docs/project-charter.md)
- [ ] update the project charter with information on the working groups
- [ ] google group link is broken
- [ ] update meeting cadence with new mtg details
- [ ] check / update Webex and dialin details as we are now using Zoom for some meetings
- [ ] add TF and Ansible repos to the project repos 
- [ ] is mailing list correct and should we add Slack Channel #CFI?

The [main readme](https://github.com/finos/compliant-financial-infrastructure/blob/dev/README.md) looks okay I think the main gap with it is doesn't cover the WG structure. I think same applies for the [contribution guide](https://github.com/finos/compliant-financial-infrastructure/blob/dev/docs/CONTRIBUTING.md)
