### ISSUE TITLE
Create IaC for OCP+GCP

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#253]
### Description of Problem:

PR finos/compliant-financial-infrastructure#235 has added a robust set of instructions for a compliant deployment of OCP on GCP. The next step for this is to add infrastructure as code to automate the process.

### Potential Solutions:

We may want to create a new terraform module based on the documentation within finos/compliant-financial-infrastructure#235

**Comment by eddie-knight** [comment]
We will be creating a new repo, and will use that repo's issue tracker for individual work items related to this effort

**Comment by devops-adeel** [comment]
- [ ] Create Terraform Module Template Repo
- [ ] README to describe the structure of the repo.
- [ ] Create modules (via template repo) for the infrastructure on GCP.
- [ ] Create module (via template repo) for the OCP foundational administration.

**Comment by mcleo-d** [comment]
@AdrianHammond - I'd like to make you aware of this issue as discussed over Slack 👍🏻

**Comment by eddie-knight** [comment]
@AdrianHammond, would you care to update this issue with next steps (or a plan) to finalize the IaC for this effort?

Additional commenters are welcome as well :+1:

**Comment by thinkl33t** [comment]
Would it be worth initially aiming at creating a compliant GCP terraform module using our new terraform template repo, then once that is working make the OCP stuff depend on that?

**Comment by mcleo-d** [comment]
@AdrianHammond and @peter-thomas-db 

It would be great to bring Deutsche Bank into the discussion on this piece of work as sponsor and champion.

Can you attend #265 to discuss on the call?

James.

**Comment by mcleo-d** [comment]
Hey @devops-adeel 👋🏻 

It would be great to get an update at #276 seeing as you seem to be owning the tasks 😄 

- https://github.com/finos/compliant-financial-infrastructure/issues/253#issuecomment-1225581625

James.

**Comment by eddie-knight** [comment]
@AdrianHammond will provide a summary of the design, which will implement Ansible to orchestrate the sequential terraform processes.

**Comment by eddie-knight** [comment]
Subsequent work is being tracked in finos/ansible-cfi-ocp#2 finos/ansible-cfi-ocp#3 and finos/ansible-cfi-ocp#4
