### ISSUE TITLE
Explore Juju Terraform Provider for CFI

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#257]
Hi @pedroleaoc and @kriscanonical 👋🏻 

I recently read [Jon Seager's LinkedIn Post](https://www.linkedin.com/posts/jnsgruk_introducing-the-juju-terraform-provider-activity-6967941754696167424-vJZn) announcing the new [Canonical Terraform Provider for Juju](https://discourse.charmhub.io/t/introducing-the-juju-terraform-provider/6939).

Can a member of the Canonical team give an overview of the Terraform provider to determine whether it can be used by CFI. In particular https://github.com/finos/compliant-financial-infrastructure/issues/212 where the Legend and Waltz Charm bundles could harness the CFI EKS service?

Your time and direction would be greatly appreciated.

James.

**Comment by mcleo-d** [comment]
Hi @pedroleaoc and @kriscanonical 👋🏻

It would be awesome if you could help schedule some of Jon's time to run through the benefits of the provider.

Many thanks,

James.

**Comment by eddie-knight** [comment]
Closing this as stale. Happy to have this reopened if it is discussed within the Reproducible Build Working Group.
