### ISSUE TITLE
Terraform Best Practices

### ISSUE THREAD

**Issue by ml4** [finos/compliant-financial-infrastructure#258]
### Description of Problem:
As a guide for users of CFI IaC, a best practices document would benefit FINOS members.
This would also help contributors aggregate guidances for users in one place.

### Potential Solutions:
The document should live in the finos/compliant_financial_infrastructure/docs directory, as this repo is the entry point for members wishing to use CFI TF modules.

The best practices for module development are somewhat in flux, so the BP doc should be considered as organic.  
HashiCorp to provide inputs in the regard.

**Comment by mcleo-d** [comment]
Hi @ml4 👋🏻 

Are you happy to champion this issue at the next CFI call - #265 

You could also raise a PR for review if you want to cut out cycles 😉 

James.

**Comment by mcleo-d** [comment]
Hi @ml4 

Does the following PR relate to this issue ... https://github.com/finos/compliant-financial-infrastructure/pull/259

It would be great to know when this issue can be closed.

Many thanks,

James.

**Comment by ml4** [comment]
Hello @mcleo-d apologies for the delay, yes it does.
