### ISSUE TITLE
Proposed changes to maintainer docs

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#264]
In order to accommodate upcoming changes that are being considered to the community structure, and based on lessons learned to date by the CFI community, the following changes are proposed to the organization of maintainers:

1. The maintainer role will become a 3 month commitment
1. If working groups exist, a minimum of one maintainer will be present within each active working group
1. Maintainers will have a set of expectations or duties clearly documented within this repository
1. At the end of each quarter, no less than one week prior to the last day of the quarter, the community will affirm a new maintainer cohort
1. Maintainers may be considered from a pool of individuals nominated by the current cohort of maintainers
1. If a maintainer wishes to continue their commitment, they may nominate themselves
1. Nominations may only be individuals who have made at least one substantial and consequential commit to merged into a CFI codebase
1. No limit is placed on the number of nominees or maintainers affirmed
1. A single GitHub issue will be used to track nominations and affirmations, though this process should be elaborated on further during this documentation process

- [ ] Community has discussed and provided feedback on the proposed revision
- [ ] Documentation in this repository has been updated to properly reflect the approved revisions

**Comment by AdrianHammond** [comment]
I wasn't aware of the previous guidelines but these look to be a good set of principals to work too.

**Comment by mcleo-d** [comment]
Hi @eddie-knight - I have labeled as `please read` and added to the CFI Kanban.

**Comment by thinkl33t** [comment]
The suggestions above feel sensible enough, i'm wondering if we need a process for community approval though. 

The silent consensus during meetings system we currently have works ok for approving meeting minutes but there's chance for a lot of interpersonal conflict here if someone believes someone else is unsuitable to be a maintainer - you may have some thoughts on this from a community manager POV @mcleo-d

**Comment by mcleo-d** [comment]
Discussed on https://github.com/finos/compliant-financial-infrastructure/issues/265 with community invited to feedback in comments.

**Comment by eddie-knight** [comment]
I've created #269 to discuss the opportunity for working groups. It _may be considered_ that the proposal above for maintainers is instead shifted to create regimentation around the working group leadership, instead of creating regimentation applying to all maintainers.
