### ISSUE TITLE
Create Working Group for policy-related outputs

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#272]
Part of #269. Please comment with suggestions to improve this list & discussion regarding how to tackle each item.

The policy working group will be responsible for maintaining all documentation related to the items we currently refer to as "Service Approval Accelerators." This will include meeting with FINOS members and CFI community members to facilitate the creation and maintenance of standards used by the other WGs to create useful tools for FINOS members.

## Action Items

- [x] Determine Working Group Mission/Vision
- [x] Decide on name for WG
- [x] Outline initial WG leadership structure
- [x] Outline initial WG meeting cadence
- [x] Create a dedicated slack channel for WG
- [ ] Document whatever resulted from this task

**Comment by eddie-knight** [comment]
Everyone - Please comment here if you like to participate in the foundational planning meeting where we will solidify the decisions.

Other comments are welcome in this issue as well.

**Comment by AdrianHammond** [comment]
Include me please @eddie-knight

**Comment by eddie-knight** [comment]
Compliant Financial Infrastructure Policy Working Group

## WG Governance/Leadership Structure

Meeting Facilitator
- Enforces structure for public meetings

Embedded Maintainer
- At least one CFI maintainer must be allocated to focus on this WG specifically
- Abdullah Garcia as the initial embedded maintainer

## Outline initial WG meeting cadence

- 1hr Monthly WG Call (offset by 2 weeks w/ All-CFI call)
- Unposted weekly huddles

## Outline initial WG meeting cadence

- 1hr Monthly WG Call (offset by 2 weeks w/ All-CFI call)
- Unposted weekly huddles
