### ISSUE TITLE
Change CFI Meeting Cadence to 1st Friday of Each Month

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#275]
Compliant Financial Infrastructure would like to propose meeting on the **1st Friday of Each Month** to fall in line with future working group meeting cadences.

**Comment by eddie-knight** [comment]
The need for this issue was raised during the planning meeting for #273

**Comment by mcleo-d** [comment]
Does the group want to change the meeting away from Friday?

**Comment by thinkl33t** [comment]
Moving away from friday afternoon would be beneficial for me if we can find a more generally acceptable timeslot

**Comment by eddie-knight** [comment]
> Does the group want to change the meeting away from Friday?

I can flex to whichever time best suits the community

**Comment by ml4** [comment]
Friday is harder for me as it's the only day I get to have less context-switched time away from customer calls to get coding done.

**Comment by mcleo-d** [comment]
@mcleo-d from FINOS to investigate a Wednesday cadence for all CFI related project meetings.

**Comment by mcleo-d** [comment]
Compliant Financial Infrastructure main project meetings have now moved to the **2nd Wednesday of Each Month** starting **Wednesday 14th December 2022 at 10am ET / 3pm GMT**.

This has now been reflected in the FINOS Community Calendar with all invited parties being moved to the new meeting cadence.

**Comment by mcleo-d** [comment]
First new meeting cadence - https://github.com/finos/compliant-financial-infrastructure/issues/290
