### ISSUE TITLE
Merge `dev` into `main`

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#277]
### Description

Can the CFI maintainers merge `dev` into `main` so the `OpenSSF Progress Badge`, plus other accepted changes, reflect correctly?

Many thanks,

James.

**Comment by eddie-knight** [comment]
- Part of #254 
- Relates to #271 in that we need to adjust how we're doing out releases to avoid this type of issue being repetetive
- Relates to #239 in that we should consider this usecase while making progress on the restructure of this repo

**Comment by abdullahgarcia** [comment]
I believe this has been addressed.
