### ISSUE TITLE
4th January 2023 - CFI : Runtime Validation Working Group

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#296]
## Date
Wednesday 4th January 2023 - 9am ET / 2pm GMT

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] https://github.com/finos/compliant-financial-infrastructure/issues/297
- [x] Working Group Discussion

### Zoom Meeting
https://zoom.us/j/98150748069?pwd=M1dVS0RvN1lVbmRQblc4bEZrTlNpUT09

Meeting ID: 981 5074 8069
Passcode: 430007

**Github Repo:** https://github.com/finos/compliant-financial-infrastructure/

**Mailing List:** Email compliant-financial-infrastructure+subscribe@finos.org to subscribe to our mailing list

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by jihed** [comment]
Hi!

**Comment by eddie-knight** [comment]
:wave: :shipit:
