### ISSUE TITLE
Determine tooling approach for Runtime Validation WG

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#297]
By 1/11 the team needs to determine one of the following courses of action for the Runtime Validation WG tooling:

1. Ad Hoc - WG will be responsible for determining the best tool for each service and configuring it to match the associated CFI policy
2. Probr - Use the existing Probr tooling as we have been thus far: Custom BDD test packs for each policy
3. Probr Fork - Strip down Probr BDD complexities to focus on tests and results and reducing overhead on BDD work

**Comment by thinkl33t** [comment]
on the CFI call i asked if it'd be worth talking to the probr community / ip owners to see if probr itself could be donated to FINOS / LF as a project, then the work to make a simplified bdd-only probr could be done under the original probr name.

**Comment by abdullahgarcia** [comment]
Decision taking regarding requirements:

- Execute a pack multiple times.

**Comment by thinkl33t** [comment]
if we're forking, we need to move to a different name, as the projects will diverge over time

**Comment by abdullahgarcia** [comment]
Probr Light

**Comment by AdrianHammond** [comment]
as an output of the discussion on #300 the two work items were agreed:

- [ ] @eddie-knight to discuss with other Probr maintainers to see if they are willing to align to how we want to take Probr forward for CFI
- [ ] our current working assumption is that we will fork and rename Probr for use by CFI

**Comment by eddie-knight** [comment]
Reached out to @iantivey and @lluuiissoo for input as the admins of Probr. @hermant0711 is a contributor who may have input as well.

The key question for the Probr admins is "Is our proposed redesign of Probr compatible with your users?"

If the proposed work is incompatible with Probr (as we expect it will be), we will create a fork that takes all the existing architecture and tests from Probr while stripping out the various BDD elements.

**Comment by eddie-knight** [comment]
Already heard back from @lluuiissoo, his perspective is that BDD is a key element of Probr that cannot be removed within the core scope of Probr. 

Closing this issue as complete, as we have determined the best course of action is to fork it.

**Comment by lluuiissoo** [comment]
Just to clarify my feedback: Current Probr implementation relies heavily on BDD godog framework to produce reports. Decoupled core+plugins architecture could make possible the implementation of additional service packs without relying on BDD paradigm, as long as interface/contract is added for consistent output (this is not done yet).
As I stated to @eddie-knight offline, it would be ideal to involve other Synechron stakeholders and SMEs (Paul Jones paulm-jones, Sandeep Kumar) to discuss and validate options and impact.
