### ISSUE TITLE
Create the mission, strategy, and approach for each WG

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#298]
We have discussed setting up a public docs site, and will need to track that work in the near future. The site should compile key information to help guide contributors and provide focus as the project moves forward.

Regardless of how long it takes us to publish this information, having it available in some format will be key as we move forward.

This work should be completed by the CFI maintainer group.

## Here are some things we may want to include for each WG:

- Why does this working group exist? 
  - This has already been created for each
- What are the main, high level objectives this group is working toward?
  - This should be a short list of objectives that contribute to the mission
- How are each of those objectives being pursued?
  - What type of activities are we doing to make progress?
  - What are some common work items?
  - How do we know when each objective is complete?
- How is work tracked relating to each of these objectives?
  - The work tracker is already set up, but needs to be documented
  - For common types of work items:
    - How do we know when the work is ready to start?
    - What are the requirements for each to be considered complete?
- What is the best way for a new contributor to begin contributing to this work?
  - We just need to clarify a practical process for new contributors to get started actively contributing

**Comment by thinkl33t** [comment]
@AdrianHammond and I are going to have a chat about this for the RI WG in the next week.

**Comment by jstclair2019** [comment]
@eddie-knight sorry, where do I find a list of WGs?

**Comment by eddie-knight** [comment]
@jstclair2019 We've been dragging our feet on updating the documentation-- too many lazy perfectionists in our group. It's on the goals for January though.

The working groups are:
- Policy WG
- Reproducible Build WG
- Runtime Validation WG

**Comment by AdrianHammond** [comment]
@eddie-knight @abdullahgarcia 

@thinkl33t and I reviewed this, created last year as group, and we think it pretty much covers what need for the RI WG.  Thoughts?

The Reproducible Infrastructure Working Group is responsible for Infrastructure as Code adhering to Service Approval Accelerators.

Outputs from this WG should be organized in a format that is ready for customers to import directly into their own registry.
In most cases, this means that a single repository exists for each IaC component.

Work items, suggestions, and concerns related to this WG are tracked [here](https://github.com/orgs/finos/projects/45).

Additional Notes:

IaC may include multiple services if necessary to properly ensure compliance of the specified service
Within the IaC Repo there must be documentation that states any CIS policies that the IAC does not implement
