### ISSUE TITLE
Set 'main' to default branch and remove 'dev'

### ISSUE THREAD

**Issue by thinkl33t** [finos/compliant-financial-infrastructure#320]
We added `dev` as a workaround for our EKS CI not getting credentials when a branch came from externally.  This is no longer a worry as the repo is laid out differently now, so we'd like to make `main` the... `main` branch again, and we never implemented a process for merging from dev to main, meaning the two have gotten out of sync often.

I discussed this on a call with @eddie-knight @AdrianHammond, and we agreed that this was the best way to proceed.

**Comment by TheJuanAndOnly99** [comment]
@eddie-knight @thinkl33t I've just changed the default branch to `main`

**Comment by eddie-knight** [comment]
We can take care of the branch cleanup from here. Thanks @TheJuanAndOnly99 !

**Comment by eddie-knight** [comment]
Whoops, got a little handsy with the buttons there. Reopening until we finish the branch cleanup.

**Comment by thinkl33t** [comment]
This still requires work to identify and merge commits that exist in `dev` but never made it into `main`

**Comment by maoo** [comment]
@thinkl33t - all done, closing issue. Thanks!
