### ISSUE TITLE
CFI RI WG Meeting: 2023-02-22

### ISSUE THREAD

**Issue by thinkl33t** [finos/compliant-financial-infrastructure#321]
## Date

Wednesday 22 02 2023 - 10am ET / 3pm GMT

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [ ] CFI Reproducible Infrastructure Working Group [Project Kanban](https://github.com/orgs/finos/projects/45) Review
- [ ] Working Group Discussion

## Decisions Made

- [ ] ...

## Action Items

- [ ] ...

### Zoom Meeting

https://zoom.us/j/97339752885?pwd=ZXQzZGdyMFRDNTgzVWJ0blZiMkJsUT09

Meeting ID: 973 3975 2885
Passcode: 614007

**Github Repo:** https://github.com/finos/compliant-financial-infrastructure/

**Mailing List:** Email compliant-financial-infrastructure+subscribe@finos.org to subscribe to our mailing list

**Comment by AdrianHammond** [comment]
Hi Y'all 👋

**Comment by thinkl33t** [comment]
Here

**Comment by eddie-knight** [comment]
👋 :shipit:

**Comment by Julia-Ritter** [comment]
Julia / FINOS 👋
