### ISSUE TITLE
Determine process for soliciting policy input

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#328]
Recent discussions have repeatedly highlighted the need for a strategic approach to soliciting input from end users.

As discussed on today's community call, we need to determine our goals before we can drill into the tactical approach. 

Once we determine the information we're hoping to get at this time, @niamhoparker has offered to support the Policy WG in tactfully engaging the right people.

**Comment by abdullahgarcia** [comment]
Thanks for formalising the issue @eddie-knight.

@niamhoparker - when can we get together to address this? Also, looking forward to seeing you in the upcoming session this Wednesday!

**Comment by jstclair2019** [comment]
Sorry if totally dumb question, but have we determined what policy areas we seek to collect? I know I've personally harped on ICT risks, but didn't think that's all.
Maybe policies on loss reserve ratios? :) Too soon?

**Comment by AdrianHammond** [comment]
Hi @jstclair2019 We are looking to get an understanding from the FSI members of FINOS so that we can determine the common security / compliance requirements that we can address via CFI. In the session last Wednesday we discussed some of the tactics to get this information (interviews and surveys) but what we did not finalise, which we should do on Wednesday, is finalise what the ask is.

**Comment by abdullahgarcia** [comment]
Brief statement to address the FINOS members in order to gain the required information.

**Comment by niamhoparker** [comment]
> Brief statement to address the FINOS members in order to gain the required information.

hi @abdullahgarcia @eddie-knight - hope you're well. following up on this. let me know timeline so i can dedicate time to this when ready. happy to join any meeting. just ping me on slack if easier too.

**Comment by eddie-knight** [comment]
Starting a slack thread to hammer out the process for this.
