### ISSUE TITLE
Create Template Repo for CFI / CCC policies

### ISSUE THREAD

**Issue by AdrianHammond** [finos/compliant-financial-infrastructure#348]
### Description of Problem:
Create a template repo that can be used for IaC/Automation for CCC policy validation

**Comment by AdrianHammond** [comment]
Todo List

- [ ] Request new template repo
- [ ] Issues Template
- [ ] PR Template
- [ ] License
- [ ] workflow skeleton
- [ ] ansible skeleton
- [ ]  .docs
- [ ] Readme.md

@eddie-knight FYI

**Comment by AdrianHammond** [comment]
@eddie-knight  - here is PR https://github.com/finos/cfi-ansible-template/pull/1 for intial template updates. Please could you review / merge.  Thanks Adrian

**Comment by eddie-knight** [comment]
Merged! Any further changes can be iterative as we use the template.
