### ISSUE TITLE
New AWS Cloud Service request AWS EventBridge

### ISSUE THREAD

**Issue by git-hub-forwork1** [finos/compliant-financial-infrastructure#36]
## Building Artefacts for AWS EventBridge

I would like input from interested parties around AWS EventBridge for the next cloud service certification artefacts for AWS.

I am providing some links to the community to review and get educated on this service if they are not already familiar.

https://aws.amazon.com/eventbridge/
https://www.youtube.com/watch?v=28B4L1fnnGM
https://www.serverless.com/blog/eventbridge-use-cases-and-tutorial/

These should provide enough high level and detail to get you started towards understanding this service and allow for collaboration on building artefacts for the Service Certification.  

The last link provides some specific detail about use cases so that it is clear this managed service is basically Cloudwatch under the covers with cron functions and a rules engine for multiple sources and destinations.

**Comment by mcleo-d** [comment]
@ColinEberhardt, @abdullahgarcia and @jonmuk

I have removed you as assignees but welcome you to collaborate on this story as handed over the the CSC group during #35 - 4 June 2020 - Cloud Service Certification Meeting.

Feel free to ask @git-hub-forwork1 more questions is and when required.

James.

**Comment by mcleo-d** [comment]
@peterrhysthomas, @pudern and @alfredtommy,

I'd like to draw your awareness to @git-hub-forwork1's AWS story if you know or have people in your organisations who are able to help?

James.

**Comment by peterrhysthomas** [comment]
Unfortunately not, we aren't looking at AWS at the moment, so I don't know of anyone who would be able to contribute.

**Comment by eddie-knight** [comment]
Closing this issue as stale. 

If anyone would like to volunteer to contribute to the development of policy and IaC related to EventBridge, please discuss that with the Policy or Reproducible Infrastructure working groups as needed.
