### ISSUE TITLE
CSC Community to Instruct and Prioritise Cloud Services Project Focus

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#63]
## Description
This GitHub Issue is an asynchronous discussion and potential vote to help instruct the Cloud Service Certification project on the next set of cloud services to be focused upon by the team.

During the Cloud Service Certification meeting on 10th September 2020 #61 the following services were called out and suggested by the group.

1. Kubernetes - #64 (Epic)
2. PostgreSQL - #80 (Epic)

---
- Redis - Pending prioritisation. Subject to team member availability.
- Prometheus
- Grafana
- MongoDB
- MySQL

Please continue the suggestions and discussion in the comments below 👇

**Comment by tmewett** [comment]
Hi! It's Tom from Codethink. I'm planning to look into creating a Service Approval Accelerator for Kubernetes on Azure.

**Comment by mcleo-d** [comment]
Welcome to the team @tmewett 👏  💯 💯 💯  

Please join us on Monday 24th September for a review of #60 and the opportunity to meet the team. I have added you to the meeting invite. 

@alfredtommy has created the following Service Approval Accelerator for Kubernetes on GCP that you might want to review - https://github.com/finos/cloud-service-certification/blob/master/gcp/gke/kubernetes.md

You can find a blank [Service Approval Accelerator template Here](https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md) that was created by @danizheleva and the team.  

If you can raise a [New Feature Request Here](https://github.com/finos/cloud-service-certification/issues/new?template=Feature_request.md) that describes the activity you're leading we'll add to the [CSC Project Kanaban](https://github.com/orgs/finos/projects/1)

We can groom the item with @peterrhysthomas later, so don't feel you need to go into too much tech detail as it's important to start tracking the work right now 👍 

🚀 🚀 🚀

**Comment by danizheleva** [comment]
We've mentioned that some services are "foundational" to many other services (such as IAM/Key Management) and we're seeing the same information across multiple templates - so maybe we could focus on one of them across the main cloud providers as a group? For example IAM on GCP/Azure/Microsoft. And then we can link to this within the higher level services (such as PostgreSQL).

**Comment by mcleo-d** [comment]
Closing old issue.
