### ISSUE TITLE
Consider Asciidoc for document markup

### ISSUE THREAD

**Issue by tmewett** [finos/compliant-financial-infrastructure#70]
Currently, documents are written in Markdown. They use a lot of tables, but Markdown table syntax is quite restrictive and doesn't let you have any multi-paragraph or block elements in a table cell. To work around this, HTML is used, which make the documents harder to read/edit in plain text.

GitHub can render a few different markup languages, and one of these is Asciidoc (with [Asciidoctor](https://asciidoctor.org/docs/asciidoc-writers-guide/); extension `.adoc`). This supports quite flexible table syntax, as well as automatic tables of contents and other more sophisticated document features, so might be worth evaluating.

**Comment by mcleo-d** [comment]
Hi @tmewett 

Please note this issue was mentioned at #77 with the following action taken ...

> @tmewett to move forward with Consider Asciidoc for document markup #70 by combining with #72 if viable and appropriate.

Cheers 🚀 🚀 🚀

**Comment by tmewett** [comment]
Just some more info on my thoughts for this: I made this issue with the assumption that there was or was going to be a standard format for the CSC documents, and was suggesting an alternative which you may prefer. If there is no standard format, then this isn't really an issue, just an individual recommendation. In this case, perhaps the issue could take the form of rewriting the template files in non-tabled Markdown or Asciidoc, which might be easier to read and write.

In any case, I have been reassigned somewhere else, so how this works into #72 will be up to my successor. :grin: Thanks!

**Comment by mcleo-d** [comment]
@J0EG to comment experiences of https://github.com/finos/cloud-service-certification/pull/97 before moving forward with Asciidoc for document markup 👍

**Comment by J0EG** [comment]
I uploaded the latest template as asciidoc and found it more efficient for documentation.

**Comment by mcleo-d** [comment]
The decision to use asciidoc has been made in #162 by @peterrhysthomas and the group.
